spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Product
    username: vatan
    password: 0111
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework: info
    org.hibernate: info